name: iOS Alpha Release

on:
  push:
    tags:
      - '*-ios'

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Archive
        working-directory: ./iosApp
        run: |
          xcodebuild -project ./FeedFlow.xcodeproj \
                      -scheme FeedFlow
                      -sdk iphoneos \
                      -configuration Release \
                      -archivePath $PWD/build/FeedFlow.xcarchive \
                      clean archive | xcpretty

      - name: Export
        working-directory: ./iosApp
        run: |
          xcodebuild -archivePath $PWD/build/FeedFlow.xcarchive \
                      -exportOptionsPlist ExportOptions.plist \
                      -exportPath $PWD/build \
                      -allowProvisioningUpdates \
                      -exportArchive | xcpretty

      - name: Upload
        env:
          APPLEID_USERNAME: ${{ secrets.APP_STORE_CONNECT_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APP_STORE_CONNECT_PASSWORD }}
        working-directory: ./iosApp
        run: |
          xcrun altool --upload-app -t ios -f build/FeedFlow.ipa -u "$APPLEID_USERNAME" -p "$APPLEID_PASSWORD" --verbose